[build]
  command = "npm run build"
  publish = "dist/client"

[functions]
  directory = "dist/server"
  node_bundler = "nft"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
