/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSamRouteImport } from './routes/_authenticated/sam'
import { Route as AuthenticatedManagerRouteImport } from './routes/_authenticated/manager'
import { Route as AuthenticatedAffiliateRouteImport } from './routes/_authenticated/affiliate'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSamIndexRouteImport } from './routes/_authenticated/sam/index'
import { Route as AuthenticatedManagerIndexRouteImport } from './routes/_authenticated/manager/index'
import { Route as AuthenticatedAffiliateIndexRouteImport } from './routes/_authenticated/affiliate/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedSamManagersRouteImport } from './routes/_authenticated/sam/managers'
import { Route as AuthenticatedSamAffiliatesRouteImport } from './routes/_authenticated/sam/affiliates'
import { Route as AuthenticatedManagerAffiliatesRouteImport } from './routes/_authenticated/manager/affiliates'
import { Route as AuthenticatedAffiliatePromoCodesRouteImport } from './routes/_authenticated/affiliate/promo-codes'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminPromoCodesRouteImport } from './routes/_authenticated/admin/promo-codes'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin/plans'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSamRoute = AuthenticatedSamRouteImport.update({
  id: '/sam',
  path: '/sam',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedManagerRoute = AuthenticatedManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAffiliateRoute = AuthenticatedAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSamIndexRoute = AuthenticatedSamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSamRoute,
} as any)
const AuthenticatedManagerIndexRoute =
  AuthenticatedManagerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedAffiliateIndexRoute =
  AuthenticatedAffiliateIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAffiliateRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSamManagersRoute =
  AuthenticatedSamManagersRouteImport.update({
    id: '/managers',
    path: '/managers',
    getParentRoute: () => AuthenticatedSamRoute,
  } as any)
const AuthenticatedSamAffiliatesRoute =
  AuthenticatedSamAffiliatesRouteImport.update({
    id: '/affiliates',
    path: '/affiliates',
    getParentRoute: () => AuthenticatedSamRoute,
  } as any)
const AuthenticatedManagerAffiliatesRoute =
  AuthenticatedManagerAffiliatesRouteImport.update({
    id: '/affiliates',
    path: '/affiliates',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedAffiliatePromoCodesRoute =
  AuthenticatedAffiliatePromoCodesRouteImport.update({
    id: '/promo-codes',
    path: '/promo-codes',
    getParentRoute: () => AuthenticatedAffiliateRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPromoCodesRoute =
  AuthenticatedAdminPromoCodesRouteImport.update({
    id: '/promo-codes',
    path: '/promo-codes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/affiliate': typeof AuthenticatedAffiliateRouteWithChildren
  '/manager': typeof AuthenticatedManagerRouteWithChildren
  '/sam': typeof AuthenticatedSamRouteWithChildren
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/promo-codes': typeof AuthenticatedAdminPromoCodesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/affiliate/promo-codes': typeof AuthenticatedAffiliatePromoCodesRoute
  '/manager/affiliates': typeof AuthenticatedManagerAffiliatesRoute
  '/sam/affiliates': typeof AuthenticatedSamAffiliatesRoute
  '/sam/managers': typeof AuthenticatedSamManagersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/affiliate/': typeof AuthenticatedAffiliateIndexRoute
  '/manager/': typeof AuthenticatedManagerIndexRoute
  '/sam/': typeof AuthenticatedSamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/promo-codes': typeof AuthenticatedAdminPromoCodesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/affiliate/promo-codes': typeof AuthenticatedAffiliatePromoCodesRoute
  '/manager/affiliates': typeof AuthenticatedManagerAffiliatesRoute
  '/sam/affiliates': typeof AuthenticatedSamAffiliatesRoute
  '/sam/managers': typeof AuthenticatedSamManagersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/affiliate': typeof AuthenticatedAffiliateIndexRoute
  '/manager': typeof AuthenticatedManagerIndexRoute
  '/sam': typeof AuthenticatedSamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/affiliate': typeof AuthenticatedAffiliateRouteWithChildren
  '/_authenticated/manager': typeof AuthenticatedManagerRouteWithChildren
  '/_authenticated/sam': typeof AuthenticatedSamRouteWithChildren
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/admin/promo-codes': typeof AuthenticatedAdminPromoCodesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/affiliate/promo-codes': typeof AuthenticatedAffiliatePromoCodesRoute
  '/_authenticated/manager/affiliates': typeof AuthenticatedManagerAffiliatesRoute
  '/_authenticated/sam/affiliates': typeof AuthenticatedSamAffiliatesRoute
  '/_authenticated/sam/managers': typeof AuthenticatedSamManagersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/affiliate/': typeof AuthenticatedAffiliateIndexRoute
  '/_authenticated/manager/': typeof AuthenticatedManagerIndexRoute
  '/_authenticated/sam/': typeof AuthenticatedSamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/admin'
    | '/affiliate'
    | '/manager'
    | '/sam'
    | '/admin/plans'
    | '/admin/promo-codes'
    | '/admin/users'
    | '/affiliate/promo-codes'
    | '/manager/affiliates'
    | '/sam/affiliates'
    | '/sam/managers'
    | '/admin/'
    | '/affiliate/'
    | '/manager/'
    | '/sam/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/admin/plans'
    | '/admin/promo-codes'
    | '/admin/users'
    | '/affiliate/promo-codes'
    | '/manager/affiliates'
    | '/sam/affiliates'
    | '/sam/managers'
    | '/admin'
    | '/affiliate'
    | '/manager'
    | '/sam'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/affiliate'
    | '/_authenticated/manager'
    | '/_authenticated/sam'
    | '/_authenticated/admin/plans'
    | '/_authenticated/admin/promo-codes'
    | '/_authenticated/admin/users'
    | '/_authenticated/affiliate/promo-codes'
    | '/_authenticated/manager/affiliates'
    | '/_authenticated/sam/affiliates'
    | '/_authenticated/sam/managers'
    | '/_authenticated/admin/'
    | '/_authenticated/affiliate/'
    | '/_authenticated/manager/'
    | '/_authenticated/sam/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sam': {
      id: '/_authenticated/sam'
      path: '/sam'
      fullPath: '/sam'
      preLoaderRoute: typeof AuthenticatedSamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager': {
      id: '/_authenticated/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/affiliate': {
      id: '/_authenticated/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AuthenticatedAffiliateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sam/': {
      id: '/_authenticated/sam/'
      path: '/'
      fullPath: '/sam/'
      preLoaderRoute: typeof AuthenticatedSamIndexRouteImport
      parentRoute: typeof AuthenticatedSamRoute
    }
    '/_authenticated/manager/': {
      id: '/_authenticated/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof AuthenticatedManagerIndexRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/affiliate/': {
      id: '/_authenticated/affiliate/'
      path: '/'
      fullPath: '/affiliate/'
      preLoaderRoute: typeof AuthenticatedAffiliateIndexRouteImport
      parentRoute: typeof AuthenticatedAffiliateRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/sam/managers': {
      id: '/_authenticated/sam/managers'
      path: '/managers'
      fullPath: '/sam/managers'
      preLoaderRoute: typeof AuthenticatedSamManagersRouteImport
      parentRoute: typeof AuthenticatedSamRoute
    }
    '/_authenticated/sam/affiliates': {
      id: '/_authenticated/sam/affiliates'
      path: '/affiliates'
      fullPath: '/sam/affiliates'
      preLoaderRoute: typeof AuthenticatedSamAffiliatesRouteImport
      parentRoute: typeof AuthenticatedSamRoute
    }
    '/_authenticated/manager/affiliates': {
      id: '/_authenticated/manager/affiliates'
      path: '/affiliates'
      fullPath: '/manager/affiliates'
      preLoaderRoute: typeof AuthenticatedManagerAffiliatesRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/affiliate/promo-codes': {
      id: '/_authenticated/affiliate/promo-codes'
      path: '/promo-codes'
      fullPath: '/affiliate/promo-codes'
      preLoaderRoute: typeof AuthenticatedAffiliatePromoCodesRouteImport
      parentRoute: typeof AuthenticatedAffiliateRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/promo-codes': {
      id: '/_authenticated/admin/promo-codes'
      path: '/promo-codes'
      fullPath: '/admin/promo-codes'
      preLoaderRoute: typeof AuthenticatedAdminPromoCodesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedAdminPromoCodesRoute: typeof AuthenticatedAdminPromoCodesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
  AuthenticatedAdminPromoCodesRoute: AuthenticatedAdminPromoCodesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAffiliateRouteChildren {
  AuthenticatedAffiliatePromoCodesRoute: typeof AuthenticatedAffiliatePromoCodesRoute
  AuthenticatedAffiliateIndexRoute: typeof AuthenticatedAffiliateIndexRoute
}

const AuthenticatedAffiliateRouteChildren: AuthenticatedAffiliateRouteChildren =
  {
    AuthenticatedAffiliatePromoCodesRoute:
      AuthenticatedAffiliatePromoCodesRoute,
    AuthenticatedAffiliateIndexRoute: AuthenticatedAffiliateIndexRoute,
  }

const AuthenticatedAffiliateRouteWithChildren =
  AuthenticatedAffiliateRoute._addFileChildren(
    AuthenticatedAffiliateRouteChildren,
  )

interface AuthenticatedManagerRouteChildren {
  AuthenticatedManagerAffiliatesRoute: typeof AuthenticatedManagerAffiliatesRoute
  AuthenticatedManagerIndexRoute: typeof AuthenticatedManagerIndexRoute
}

const AuthenticatedManagerRouteChildren: AuthenticatedManagerRouteChildren = {
  AuthenticatedManagerAffiliatesRoute: AuthenticatedManagerAffiliatesRoute,
  AuthenticatedManagerIndexRoute: AuthenticatedManagerIndexRoute,
}

const AuthenticatedManagerRouteWithChildren =
  AuthenticatedManagerRoute._addFileChildren(AuthenticatedManagerRouteChildren)

interface AuthenticatedSamRouteChildren {
  AuthenticatedSamAffiliatesRoute: typeof AuthenticatedSamAffiliatesRoute
  AuthenticatedSamManagersRoute: typeof AuthenticatedSamManagersRoute
  AuthenticatedSamIndexRoute: typeof AuthenticatedSamIndexRoute
}

const AuthenticatedSamRouteChildren: AuthenticatedSamRouteChildren = {
  AuthenticatedSamAffiliatesRoute: AuthenticatedSamAffiliatesRoute,
  AuthenticatedSamManagersRoute: AuthenticatedSamManagersRoute,
  AuthenticatedSamIndexRoute: AuthenticatedSamIndexRoute,
}

const AuthenticatedSamRouteWithChildren =
  AuthenticatedSamRoute._addFileChildren(AuthenticatedSamRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAffiliateRoute: typeof AuthenticatedAffiliateRouteWithChildren
  AuthenticatedManagerRoute: typeof AuthenticatedManagerRouteWithChildren
  AuthenticatedSamRoute: typeof AuthenticatedSamRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAffiliateRoute: AuthenticatedAffiliateRouteWithChildren,
  AuthenticatedManagerRoute: AuthenticatedManagerRouteWithChildren,
  AuthenticatedSamRoute: AuthenticatedSamRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
