/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutCancelRouteImport } from './routes/checkout.cancel'
import { Route as AuthenticatedSamRouteImport } from './routes/_authenticated/sam'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedManagerRouteImport } from './routes/_authenticated/manager'
import { Route as AuthenticatedAffiliateRouteImport } from './routes/_authenticated/affiliate'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSamIndexRouteImport } from './routes/_authenticated/sam/index'
import { Route as AuthenticatedManagerIndexRouteImport } from './routes/_authenticated/manager/index'
import { Route as AuthenticatedAffiliateIndexRouteImport } from './routes/_authenticated/affiliate/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiCustomerPlansRouteImport } from './routes/api/customer/plans'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings.notifications'
import { Route as AuthenticatedSamReportsRouteImport } from './routes/_authenticated/sam/reports'
import { Route as AuthenticatedSamPromoCodesRouteImport } from './routes/_authenticated/sam/promo-codes'
import { Route as AuthenticatedSamPayoutsRouteImport } from './routes/_authenticated/sam/payouts'
import { Route as AuthenticatedSamManagersRouteImport } from './routes/_authenticated/sam/managers'
import { Route as AuthenticatedSamAffiliatesRouteImport } from './routes/_authenticated/sam/affiliates'
import { Route as AuthenticatedManagerSubscribersRouteImport } from './routes/_authenticated/manager/subscribers'
import { Route as AuthenticatedManagerReportsRouteImport } from './routes/_authenticated/manager/reports'
import { Route as AuthenticatedManagerAffiliatesRouteImport } from './routes/_authenticated/manager/affiliates'
import { Route as AuthenticatedAffiliateSubscribersRouteImport } from './routes/_authenticated/affiliate/subscribers'
import { Route as AuthenticatedAffiliateMyCodeRouteImport } from './routes/_authenticated/affiliate/my-code'
import { Route as AuthenticatedAffiliateEarningsRouteImport } from './routes/_authenticated/affiliate/earnings'
import { Route as AuthenticatedAffiliateAnalyticsRouteImport } from './routes/_authenticated/affiliate/analytics'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSystemRouteImport } from './routes/_authenticated/admin/system'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminSamsRouteImport } from './routes/_authenticated/admin/sams'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminPromoCodesRouteImport } from './routes/_authenticated/admin/promo-codes'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin/plans'
import { Route as AuthenticatedAdminPayoutsRouteImport } from './routes/_authenticated/admin/payouts'
import { Route as AuthenticatedAdminFraudRouteImport } from './routes/_authenticated/admin/fraud'
import { Route as AuthenticatedAdminEmailsRouteImport } from './routes/_authenticated/admin/emails'
import { Route as AuthenticatedAdminAuditLogsRouteImport } from './routes/_authenticated/admin/audit-logs'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'
import { Route as ApiPublicHooksRetryEmailsRouteImport } from './routes/api/public/hooks/retry-emails'
import { Route as ApiPublicHooksClearCommissionsRouteImport } from './routes/api/public/hooks/clear-commissions'
import { Route as ApiCustomerSubscriptionReactivateRouteImport } from './routes/api/customer/subscription.reactivate'
import { Route as ApiCustomerSubscriptionCreateRouteImport } from './routes/api/customer/subscription.create'
import { Route as ApiCustomerSubscriptionCancelRouteImport } from './routes/api/customer/subscription.cancel'
import { Route as ApiCustomerSubscriptionIdRouteImport } from './routes/api/customer/subscription.$id'
import { Route as ApiCustomerInvoicesCustomerIdRouteImport } from './routes/api/customer/invoices.$customerId'
import { Route as ApiCustomerCouponValidateRouteImport } from './routes/api/customer/coupon.validate'
import { Route as ApiCustomerBillingUpdatePaymentMethodRouteImport } from './routes/api/customer/billing.update-payment-method'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSamRoute = AuthenticatedSamRouteImport.update({
  id: '/sam',
  path: '/sam',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerRoute = AuthenticatedManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAffiliateRoute = AuthenticatedAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSamIndexRoute = AuthenticatedSamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSamRoute,
} as any)
const AuthenticatedManagerIndexRoute =
  AuthenticatedManagerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedAffiliateIndexRoute =
  AuthenticatedAffiliateIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAffiliateRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiCustomerPlansRoute = ApiCustomerPlansRouteImport.update({
  id: '/api/customer/plans',
  path: '/api/customer/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSamReportsRoute = AuthenticatedSamReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedSamRoute,
} as any)
const AuthenticatedSamPromoCodesRoute =
  AuthenticatedSamPromoCodesRouteImport.update({
    id: '/promo-codes',
    path: '/promo-codes',
    getParentRoute: () => AuthenticatedSamRoute,
  } as any)
const AuthenticatedSamPayoutsRoute = AuthenticatedSamPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AuthenticatedSamRoute,
} as any)
const AuthenticatedSamManagersRoute =
  AuthenticatedSamManagersRouteImport.update({
    id: '/managers',
    path: '/managers',
    getParentRoute: () => AuthenticatedSamRoute,
  } as any)
const AuthenticatedSamAffiliatesRoute =
  AuthenticatedSamAffiliatesRouteImport.update({
    id: '/affiliates',
    path: '/affiliates',
    getParentRoute: () => AuthenticatedSamRoute,
  } as any)
const AuthenticatedManagerSubscribersRoute =
  AuthenticatedManagerSubscribersRouteImport.update({
    id: '/subscribers',
    path: '/subscribers',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerReportsRoute =
  AuthenticatedManagerReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerAffiliatesRoute =
  AuthenticatedManagerAffiliatesRouteImport.update({
    id: '/affiliates',
    path: '/affiliates',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedAffiliateSubscribersRoute =
  AuthenticatedAffiliateSubscribersRouteImport.update({
    id: '/subscribers',
    path: '/subscribers',
    getParentRoute: () => AuthenticatedAffiliateRoute,
  } as any)
const AuthenticatedAffiliateMyCodeRoute =
  AuthenticatedAffiliateMyCodeRouteImport.update({
    id: '/my-code',
    path: '/my-code',
    getParentRoute: () => AuthenticatedAffiliateRoute,
  } as any)
const AuthenticatedAffiliateEarningsRoute =
  AuthenticatedAffiliateEarningsRouteImport.update({
    id: '/earnings',
    path: '/earnings',
    getParentRoute: () => AuthenticatedAffiliateRoute,
  } as any)
const AuthenticatedAffiliateAnalyticsRoute =
  AuthenticatedAffiliateAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAffiliateRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSystemRoute =
  AuthenticatedAdminSystemRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSamsRoute = AuthenticatedAdminSamsRouteImport.update({
  id: '/sams',
  path: '/sams',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPromoCodesRoute =
  AuthenticatedAdminPromoCodesRouteImport.update({
    id: '/promo-codes',
    path: '/promo-codes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPayoutsRoute =
  AuthenticatedAdminPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFraudRoute = AuthenticatedAdminFraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEmailsRoute =
  AuthenticatedAdminEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditLogsRoute =
  AuthenticatedAdminAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRetryEmailsRoute =
  ApiPublicHooksRetryEmailsRouteImport.update({
    id: '/api/public/hooks/retry-emails',
    path: '/api/public/hooks/retry-emails',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksClearCommissionsRoute =
  ApiPublicHooksClearCommissionsRouteImport.update({
    id: '/api/public/hooks/clear-commissions',
    path: '/api/public/hooks/clear-commissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCustomerSubscriptionReactivateRoute =
  ApiCustomerSubscriptionReactivateRouteImport.update({
    id: '/api/customer/subscription/reactivate',
    path: '/api/customer/subscription/reactivate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCustomerSubscriptionCreateRoute =
  ApiCustomerSubscriptionCreateRouteImport.update({
    id: '/api/customer/subscription/create',
    path: '/api/customer/subscription/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCustomerSubscriptionCancelRoute =
  ApiCustomerSubscriptionCancelRouteImport.update({
    id: '/api/customer/subscription/cancel',
    path: '/api/customer/subscription/cancel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCustomerSubscriptionIdRoute =
  ApiCustomerSubscriptionIdRouteImport.update({
    id: '/api/customer/subscription/$id',
    path: '/api/customer/subscription/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCustomerInvoicesCustomerIdRoute =
  ApiCustomerInvoicesCustomerIdRouteImport.update({
    id: '/api/customer/invoices/$customerId',
    path: '/api/customer/invoices/$customerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCustomerCouponValidateRoute =
  ApiCustomerCouponValidateRouteImport.update({
    id: '/api/customer/coupon/validate',
    path: '/api/customer/coupon/validate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCustomerBillingUpdatePaymentMethodRoute =
  ApiCustomerBillingUpdatePaymentMethodRouteImport.update({
    id: '/api/customer/billing/update-payment-method',
    path: '/api/customer/billing/update-payment-method',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/affiliate': typeof AuthenticatedAffiliateRouteWithChildren
  '/manager': typeof AuthenticatedManagerRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/sam': typeof AuthenticatedSamRouteWithChildren
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/fraud': typeof AuthenticatedAdminFraudRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/promo-codes': typeof AuthenticatedAdminPromoCodesRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/sams': typeof AuthenticatedAdminSamsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/system': typeof AuthenticatedAdminSystemRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/affiliate/analytics': typeof AuthenticatedAffiliateAnalyticsRoute
  '/affiliate/earnings': typeof AuthenticatedAffiliateEarningsRoute
  '/affiliate/my-code': typeof AuthenticatedAffiliateMyCodeRoute
  '/affiliate/subscribers': typeof AuthenticatedAffiliateSubscribersRoute
  '/manager/affiliates': typeof AuthenticatedManagerAffiliatesRoute
  '/manager/reports': typeof AuthenticatedManagerReportsRoute
  '/manager/subscribers': typeof AuthenticatedManagerSubscribersRoute
  '/sam/affiliates': typeof AuthenticatedSamAffiliatesRoute
  '/sam/managers': typeof AuthenticatedSamManagersRoute
  '/sam/payouts': typeof AuthenticatedSamPayoutsRoute
  '/sam/promo-codes': typeof AuthenticatedSamPromoCodesRoute
  '/sam/reports': typeof AuthenticatedSamReportsRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/api/customer/plans': typeof ApiCustomerPlansRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/affiliate/': typeof AuthenticatedAffiliateIndexRoute
  '/manager/': typeof AuthenticatedManagerIndexRoute
  '/sam/': typeof AuthenticatedSamIndexRoute
  '/api/customer/billing/update-payment-method': typeof ApiCustomerBillingUpdatePaymentMethodRoute
  '/api/customer/coupon/validate': typeof ApiCustomerCouponValidateRoute
  '/api/customer/invoices/$customerId': typeof ApiCustomerInvoicesCustomerIdRoute
  '/api/customer/subscription/$id': typeof ApiCustomerSubscriptionIdRoute
  '/api/customer/subscription/cancel': typeof ApiCustomerSubscriptionCancelRoute
  '/api/customer/subscription/create': typeof ApiCustomerSubscriptionCreateRoute
  '/api/customer/subscription/reactivate': typeof ApiCustomerSubscriptionReactivateRoute
  '/api/public/hooks/clear-commissions': typeof ApiPublicHooksClearCommissionsRoute
  '/api/public/hooks/retry-emails': typeof ApiPublicHooksRetryEmailsRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/fraud': typeof AuthenticatedAdminFraudRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/promo-codes': typeof AuthenticatedAdminPromoCodesRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/sams': typeof AuthenticatedAdminSamsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/system': typeof AuthenticatedAdminSystemRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/affiliate/analytics': typeof AuthenticatedAffiliateAnalyticsRoute
  '/affiliate/earnings': typeof AuthenticatedAffiliateEarningsRoute
  '/affiliate/my-code': typeof AuthenticatedAffiliateMyCodeRoute
  '/affiliate/subscribers': typeof AuthenticatedAffiliateSubscribersRoute
  '/manager/affiliates': typeof AuthenticatedManagerAffiliatesRoute
  '/manager/reports': typeof AuthenticatedManagerReportsRoute
  '/manager/subscribers': typeof AuthenticatedManagerSubscribersRoute
  '/sam/affiliates': typeof AuthenticatedSamAffiliatesRoute
  '/sam/managers': typeof AuthenticatedSamManagersRoute
  '/sam/payouts': typeof AuthenticatedSamPayoutsRoute
  '/sam/promo-codes': typeof AuthenticatedSamPromoCodesRoute
  '/sam/reports': typeof AuthenticatedSamReportsRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/api/customer/plans': typeof ApiCustomerPlansRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/affiliate': typeof AuthenticatedAffiliateIndexRoute
  '/manager': typeof AuthenticatedManagerIndexRoute
  '/sam': typeof AuthenticatedSamIndexRoute
  '/api/customer/billing/update-payment-method': typeof ApiCustomerBillingUpdatePaymentMethodRoute
  '/api/customer/coupon/validate': typeof ApiCustomerCouponValidateRoute
  '/api/customer/invoices/$customerId': typeof ApiCustomerInvoicesCustomerIdRoute
  '/api/customer/subscription/$id': typeof ApiCustomerSubscriptionIdRoute
  '/api/customer/subscription/cancel': typeof ApiCustomerSubscriptionCancelRoute
  '/api/customer/subscription/create': typeof ApiCustomerSubscriptionCreateRoute
  '/api/customer/subscription/reactivate': typeof ApiCustomerSubscriptionReactivateRoute
  '/api/public/hooks/clear-commissions': typeof ApiPublicHooksClearCommissionsRoute
  '/api/public/hooks/retry-emails': typeof ApiPublicHooksRetryEmailsRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/affiliate': typeof AuthenticatedAffiliateRouteWithChildren
  '/_authenticated/manager': typeof AuthenticatedManagerRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/sam': typeof AuthenticatedSamRouteWithChildren
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/_authenticated/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/_authenticated/admin/fraud': typeof AuthenticatedAdminFraudRoute
  '/_authenticated/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/admin/promo-codes': typeof AuthenticatedAdminPromoCodesRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/sams': typeof AuthenticatedAdminSamsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/system': typeof AuthenticatedAdminSystemRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/affiliate/analytics': typeof AuthenticatedAffiliateAnalyticsRoute
  '/_authenticated/affiliate/earnings': typeof AuthenticatedAffiliateEarningsRoute
  '/_authenticated/affiliate/my-code': typeof AuthenticatedAffiliateMyCodeRoute
  '/_authenticated/affiliate/subscribers': typeof AuthenticatedAffiliateSubscribersRoute
  '/_authenticated/manager/affiliates': typeof AuthenticatedManagerAffiliatesRoute
  '/_authenticated/manager/reports': typeof AuthenticatedManagerReportsRoute
  '/_authenticated/manager/subscribers': typeof AuthenticatedManagerSubscribersRoute
  '/_authenticated/sam/affiliates': typeof AuthenticatedSamAffiliatesRoute
  '/_authenticated/sam/managers': typeof AuthenticatedSamManagersRoute
  '/_authenticated/sam/payouts': typeof AuthenticatedSamPayoutsRoute
  '/_authenticated/sam/promo-codes': typeof AuthenticatedSamPromoCodesRoute
  '/_authenticated/sam/reports': typeof AuthenticatedSamReportsRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/api/customer/plans': typeof ApiCustomerPlansRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/affiliate/': typeof AuthenticatedAffiliateIndexRoute
  '/_authenticated/manager/': typeof AuthenticatedManagerIndexRoute
  '/_authenticated/sam/': typeof AuthenticatedSamIndexRoute
  '/api/customer/billing/update-payment-method': typeof ApiCustomerBillingUpdatePaymentMethodRoute
  '/api/customer/coupon/validate': typeof ApiCustomerCouponValidateRoute
  '/api/customer/invoices/$customerId': typeof ApiCustomerInvoicesCustomerIdRoute
  '/api/customer/subscription/$id': typeof ApiCustomerSubscriptionIdRoute
  '/api/customer/subscription/cancel': typeof ApiCustomerSubscriptionCancelRoute
  '/api/customer/subscription/create': typeof ApiCustomerSubscriptionCreateRoute
  '/api/customer/subscription/reactivate': typeof ApiCustomerSubscriptionReactivateRoute
  '/api/public/hooks/clear-commissions': typeof ApiPublicHooksClearCommissionsRoute
  '/api/public/hooks/retry-emails': typeof ApiPublicHooksRetryEmailsRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pricing'
    | '/sitemap.xml'
    | '/admin'
    | '/affiliate'
    | '/manager'
    | '/notifications'
    | '/sam'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/emails'
    | '/admin/fraud'
    | '/admin/payouts'
    | '/admin/plans'
    | '/admin/promo-codes'
    | '/admin/reports'
    | '/admin/sams'
    | '/admin/settings'
    | '/admin/system'
    | '/admin/users'
    | '/affiliate/analytics'
    | '/affiliate/earnings'
    | '/affiliate/my-code'
    | '/affiliate/subscribers'
    | '/manager/affiliates'
    | '/manager/reports'
    | '/manager/subscribers'
    | '/sam/affiliates'
    | '/sam/managers'
    | '/sam/payouts'
    | '/sam/promo-codes'
    | '/sam/reports'
    | '/settings/notifications'
    | '/api/customer/plans'
    | '/admin/'
    | '/affiliate/'
    | '/manager/'
    | '/sam/'
    | '/api/customer/billing/update-payment-method'
    | '/api/customer/coupon/validate'
    | '/api/customer/invoices/$customerId'
    | '/api/customer/subscription/$id'
    | '/api/customer/subscription/cancel'
    | '/api/customer/subscription/create'
    | '/api/customer/subscription/reactivate'
    | '/api/public/hooks/clear-commissions'
    | '/api/public/hooks/retry-emails'
    | '/api/public/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/sitemap.xml'
    | '/notifications'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/emails'
    | '/admin/fraud'
    | '/admin/payouts'
    | '/admin/plans'
    | '/admin/promo-codes'
    | '/admin/reports'
    | '/admin/sams'
    | '/admin/settings'
    | '/admin/system'
    | '/admin/users'
    | '/affiliate/analytics'
    | '/affiliate/earnings'
    | '/affiliate/my-code'
    | '/affiliate/subscribers'
    | '/manager/affiliates'
    | '/manager/reports'
    | '/manager/subscribers'
    | '/sam/affiliates'
    | '/sam/managers'
    | '/sam/payouts'
    | '/sam/promo-codes'
    | '/sam/reports'
    | '/settings/notifications'
    | '/api/customer/plans'
    | '/admin'
    | '/affiliate'
    | '/manager'
    | '/sam'
    | '/api/customer/billing/update-payment-method'
    | '/api/customer/coupon/validate'
    | '/api/customer/invoices/$customerId'
    | '/api/customer/subscription/$id'
    | '/api/customer/subscription/cancel'
    | '/api/customer/subscription/create'
    | '/api/customer/subscription/reactivate'
    | '/api/public/hooks/clear-commissions'
    | '/api/public/hooks/retry-emails'
    | '/api/public/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/pricing'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/affiliate'
    | '/_authenticated/manager'
    | '/_authenticated/notifications'
    | '/_authenticated/sam'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/audit-logs'
    | '/_authenticated/admin/emails'
    | '/_authenticated/admin/fraud'
    | '/_authenticated/admin/payouts'
    | '/_authenticated/admin/plans'
    | '/_authenticated/admin/promo-codes'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/sams'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/system'
    | '/_authenticated/admin/users'
    | '/_authenticated/affiliate/analytics'
    | '/_authenticated/affiliate/earnings'
    | '/_authenticated/affiliate/my-code'
    | '/_authenticated/affiliate/subscribers'
    | '/_authenticated/manager/affiliates'
    | '/_authenticated/manager/reports'
    | '/_authenticated/manager/subscribers'
    | '/_authenticated/sam/affiliates'
    | '/_authenticated/sam/managers'
    | '/_authenticated/sam/payouts'
    | '/_authenticated/sam/promo-codes'
    | '/_authenticated/sam/reports'
    | '/_authenticated/settings/notifications'
    | '/api/customer/plans'
    | '/_authenticated/admin/'
    | '/_authenticated/affiliate/'
    | '/_authenticated/manager/'
    | '/_authenticated/sam/'
    | '/api/customer/billing/update-payment-method'
    | '/api/customer/coupon/validate'
    | '/api/customer/invoices/$customerId'
    | '/api/customer/subscription/$id'
    | '/api/customer/subscription/cancel'
    | '/api/customer/subscription/create'
    | '/api/customer/subscription/reactivate'
    | '/api/public/hooks/clear-commissions'
    | '/api/public/hooks/retry-emails'
    | '/api/public/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ApiCustomerPlansRoute: typeof ApiCustomerPlansRoute
  ApiCustomerBillingUpdatePaymentMethodRoute: typeof ApiCustomerBillingUpdatePaymentMethodRoute
  ApiCustomerCouponValidateRoute: typeof ApiCustomerCouponValidateRoute
  ApiCustomerInvoicesCustomerIdRoute: typeof ApiCustomerInvoicesCustomerIdRoute
  ApiCustomerSubscriptionIdRoute: typeof ApiCustomerSubscriptionIdRoute
  ApiCustomerSubscriptionCancelRoute: typeof ApiCustomerSubscriptionCancelRoute
  ApiCustomerSubscriptionCreateRoute: typeof ApiCustomerSubscriptionCreateRoute
  ApiCustomerSubscriptionReactivateRoute: typeof ApiCustomerSubscriptionReactivateRoute
  ApiPublicHooksClearCommissionsRoute: typeof ApiPublicHooksClearCommissionsRoute
  ApiPublicHooksRetryEmailsRoute: typeof ApiPublicHooksRetryEmailsRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sam': {
      id: '/_authenticated/sam'
      path: '/sam'
      fullPath: '/sam'
      preLoaderRoute: typeof AuthenticatedSamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager': {
      id: '/_authenticated/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/affiliate': {
      id: '/_authenticated/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AuthenticatedAffiliateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sam/': {
      id: '/_authenticated/sam/'
      path: '/'
      fullPath: '/sam/'
      preLoaderRoute: typeof AuthenticatedSamIndexRouteImport
      parentRoute: typeof AuthenticatedSamRoute
    }
    '/_authenticated/manager/': {
      id: '/_authenticated/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof AuthenticatedManagerIndexRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/affiliate/': {
      id: '/_authenticated/affiliate/'
      path: '/'
      fullPath: '/affiliate/'
      preLoaderRoute: typeof AuthenticatedAffiliateIndexRouteImport
      parentRoute: typeof AuthenticatedAffiliateRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/customer/plans': {
      id: '/api/customer/plans'
      path: '/api/customer/plans'
      fullPath: '/api/customer/plans'
      preLoaderRoute: typeof ApiCustomerPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sam/reports': {
      id: '/_authenticated/sam/reports'
      path: '/reports'
      fullPath: '/sam/reports'
      preLoaderRoute: typeof AuthenticatedSamReportsRouteImport
      parentRoute: typeof AuthenticatedSamRoute
    }
    '/_authenticated/sam/promo-codes': {
      id: '/_authenticated/sam/promo-codes'
      path: '/promo-codes'
      fullPath: '/sam/promo-codes'
      preLoaderRoute: typeof AuthenticatedSamPromoCodesRouteImport
      parentRoute: typeof AuthenticatedSamRoute
    }
    '/_authenticated/sam/payouts': {
      id: '/_authenticated/sam/payouts'
      path: '/payouts'
      fullPath: '/sam/payouts'
      preLoaderRoute: typeof AuthenticatedSamPayoutsRouteImport
      parentRoute: typeof AuthenticatedSamRoute
    }
    '/_authenticated/sam/managers': {
      id: '/_authenticated/sam/managers'
      path: '/managers'
      fullPath: '/sam/managers'
      preLoaderRoute: typeof AuthenticatedSamManagersRouteImport
      parentRoute: typeof AuthenticatedSamRoute
    }
    '/_authenticated/sam/affiliates': {
      id: '/_authenticated/sam/affiliates'
      path: '/affiliates'
      fullPath: '/sam/affiliates'
      preLoaderRoute: typeof AuthenticatedSamAffiliatesRouteImport
      parentRoute: typeof AuthenticatedSamRoute
    }
    '/_authenticated/manager/subscribers': {
      id: '/_authenticated/manager/subscribers'
      path: '/subscribers'
      fullPath: '/manager/subscribers'
      preLoaderRoute: typeof AuthenticatedManagerSubscribersRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/reports': {
      id: '/_authenticated/manager/reports'
      path: '/reports'
      fullPath: '/manager/reports'
      preLoaderRoute: typeof AuthenticatedManagerReportsRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/affiliates': {
      id: '/_authenticated/manager/affiliates'
      path: '/affiliates'
      fullPath: '/manager/affiliates'
      preLoaderRoute: typeof AuthenticatedManagerAffiliatesRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/affiliate/subscribers': {
      id: '/_authenticated/affiliate/subscribers'
      path: '/subscribers'
      fullPath: '/affiliate/subscribers'
      preLoaderRoute: typeof AuthenticatedAffiliateSubscribersRouteImport
      parentRoute: typeof AuthenticatedAffiliateRoute
    }
    '/_authenticated/affiliate/my-code': {
      id: '/_authenticated/affiliate/my-code'
      path: '/my-code'
      fullPath: '/affiliate/my-code'
      preLoaderRoute: typeof AuthenticatedAffiliateMyCodeRouteImport
      parentRoute: typeof AuthenticatedAffiliateRoute
    }
    '/_authenticated/affiliate/earnings': {
      id: '/_authenticated/affiliate/earnings'
      path: '/earnings'
      fullPath: '/affiliate/earnings'
      preLoaderRoute: typeof AuthenticatedAffiliateEarningsRouteImport
      parentRoute: typeof AuthenticatedAffiliateRoute
    }
    '/_authenticated/affiliate/analytics': {
      id: '/_authenticated/affiliate/analytics'
      path: '/analytics'
      fullPath: '/affiliate/analytics'
      preLoaderRoute: typeof AuthenticatedAffiliateAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAffiliateRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/system': {
      id: '/_authenticated/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AuthenticatedAdminSystemRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sams': {
      id: '/_authenticated/admin/sams'
      path: '/sams'
      fullPath: '/admin/sams'
      preLoaderRoute: typeof AuthenticatedAdminSamsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/promo-codes': {
      id: '/_authenticated/admin/promo-codes'
      path: '/promo-codes'
      fullPath: '/admin/promo-codes'
      preLoaderRoute: typeof AuthenticatedAdminPromoCodesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payouts': {
      id: '/_authenticated/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AuthenticatedAdminPayoutsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fraud': {
      id: '/_authenticated/admin/fraud'
      path: '/fraud'
      fullPath: '/admin/fraud'
      preLoaderRoute: typeof AuthenticatedAdminFraudRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/emails': {
      id: '/_authenticated/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AuthenticatedAdminEmailsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit-logs': {
      id: '/_authenticated/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/retry-emails': {
      id: '/api/public/hooks/retry-emails'
      path: '/api/public/hooks/retry-emails'
      fullPath: '/api/public/hooks/retry-emails'
      preLoaderRoute: typeof ApiPublicHooksRetryEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/clear-commissions': {
      id: '/api/public/hooks/clear-commissions'
      path: '/api/public/hooks/clear-commissions'
      fullPath: '/api/public/hooks/clear-commissions'
      preLoaderRoute: typeof ApiPublicHooksClearCommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer/subscription/reactivate': {
      id: '/api/customer/subscription/reactivate'
      path: '/api/customer/subscription/reactivate'
      fullPath: '/api/customer/subscription/reactivate'
      preLoaderRoute: typeof ApiCustomerSubscriptionReactivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer/subscription/create': {
      id: '/api/customer/subscription/create'
      path: '/api/customer/subscription/create'
      fullPath: '/api/customer/subscription/create'
      preLoaderRoute: typeof ApiCustomerSubscriptionCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer/subscription/cancel': {
      id: '/api/customer/subscription/cancel'
      path: '/api/customer/subscription/cancel'
      fullPath: '/api/customer/subscription/cancel'
      preLoaderRoute: typeof ApiCustomerSubscriptionCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer/subscription/$id': {
      id: '/api/customer/subscription/$id'
      path: '/api/customer/subscription/$id'
      fullPath: '/api/customer/subscription/$id'
      preLoaderRoute: typeof ApiCustomerSubscriptionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer/invoices/$customerId': {
      id: '/api/customer/invoices/$customerId'
      path: '/api/customer/invoices/$customerId'
      fullPath: '/api/customer/invoices/$customerId'
      preLoaderRoute: typeof ApiCustomerInvoicesCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer/coupon/validate': {
      id: '/api/customer/coupon/validate'
      path: '/api/customer/coupon/validate'
      fullPath: '/api/customer/coupon/validate'
      preLoaderRoute: typeof ApiCustomerCouponValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer/billing/update-payment-method': {
      id: '/api/customer/billing/update-payment-method'
      path: '/api/customer/billing/update-payment-method'
      fullPath: '/api/customer/billing/update-payment-method'
      preLoaderRoute: typeof ApiCustomerBillingUpdatePaymentMethodRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAuditLogsRoute: typeof AuthenticatedAdminAuditLogsRoute
  AuthenticatedAdminEmailsRoute: typeof AuthenticatedAdminEmailsRoute
  AuthenticatedAdminFraudRoute: typeof AuthenticatedAdminFraudRoute
  AuthenticatedAdminPayoutsRoute: typeof AuthenticatedAdminPayoutsRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedAdminPromoCodesRoute: typeof AuthenticatedAdminPromoCodesRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSamsRoute: typeof AuthenticatedAdminSamsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSystemRoute: typeof AuthenticatedAdminSystemRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAuditLogsRoute: AuthenticatedAdminAuditLogsRoute,
  AuthenticatedAdminEmailsRoute: AuthenticatedAdminEmailsRoute,
  AuthenticatedAdminFraudRoute: AuthenticatedAdminFraudRoute,
  AuthenticatedAdminPayoutsRoute: AuthenticatedAdminPayoutsRoute,
  AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
  AuthenticatedAdminPromoCodesRoute: AuthenticatedAdminPromoCodesRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSamsRoute: AuthenticatedAdminSamsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSystemRoute: AuthenticatedAdminSystemRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAffiliateRouteChildren {
  AuthenticatedAffiliateAnalyticsRoute: typeof AuthenticatedAffiliateAnalyticsRoute
  AuthenticatedAffiliateEarningsRoute: typeof AuthenticatedAffiliateEarningsRoute
  AuthenticatedAffiliateMyCodeRoute: typeof AuthenticatedAffiliateMyCodeRoute
  AuthenticatedAffiliateSubscribersRoute: typeof AuthenticatedAffiliateSubscribersRoute
  AuthenticatedAffiliateIndexRoute: typeof AuthenticatedAffiliateIndexRoute
}

const AuthenticatedAffiliateRouteChildren: AuthenticatedAffiliateRouteChildren =
  {
    AuthenticatedAffiliateAnalyticsRoute: AuthenticatedAffiliateAnalyticsRoute,
    AuthenticatedAffiliateEarningsRoute: AuthenticatedAffiliateEarningsRoute,
    AuthenticatedAffiliateMyCodeRoute: AuthenticatedAffiliateMyCodeRoute,
    AuthenticatedAffiliateSubscribersRoute:
      AuthenticatedAffiliateSubscribersRoute,
    AuthenticatedAffiliateIndexRoute: AuthenticatedAffiliateIndexRoute,
  }

const AuthenticatedAffiliateRouteWithChildren =
  AuthenticatedAffiliateRoute._addFileChildren(
    AuthenticatedAffiliateRouteChildren,
  )

interface AuthenticatedManagerRouteChildren {
  AuthenticatedManagerAffiliatesRoute: typeof AuthenticatedManagerAffiliatesRoute
  AuthenticatedManagerReportsRoute: typeof AuthenticatedManagerReportsRoute
  AuthenticatedManagerSubscribersRoute: typeof AuthenticatedManagerSubscribersRoute
  AuthenticatedManagerIndexRoute: typeof AuthenticatedManagerIndexRoute
}

const AuthenticatedManagerRouteChildren: AuthenticatedManagerRouteChildren = {
  AuthenticatedManagerAffiliatesRoute: AuthenticatedManagerAffiliatesRoute,
  AuthenticatedManagerReportsRoute: AuthenticatedManagerReportsRoute,
  AuthenticatedManagerSubscribersRoute: AuthenticatedManagerSubscribersRoute,
  AuthenticatedManagerIndexRoute: AuthenticatedManagerIndexRoute,
}

const AuthenticatedManagerRouteWithChildren =
  AuthenticatedManagerRoute._addFileChildren(AuthenticatedManagerRouteChildren)

interface AuthenticatedSamRouteChildren {
  AuthenticatedSamAffiliatesRoute: typeof AuthenticatedSamAffiliatesRoute
  AuthenticatedSamManagersRoute: typeof AuthenticatedSamManagersRoute
  AuthenticatedSamPayoutsRoute: typeof AuthenticatedSamPayoutsRoute
  AuthenticatedSamPromoCodesRoute: typeof AuthenticatedSamPromoCodesRoute
  AuthenticatedSamReportsRoute: typeof AuthenticatedSamReportsRoute
  AuthenticatedSamIndexRoute: typeof AuthenticatedSamIndexRoute
}

const AuthenticatedSamRouteChildren: AuthenticatedSamRouteChildren = {
  AuthenticatedSamAffiliatesRoute: AuthenticatedSamAffiliatesRoute,
  AuthenticatedSamManagersRoute: AuthenticatedSamManagersRoute,
  AuthenticatedSamPayoutsRoute: AuthenticatedSamPayoutsRoute,
  AuthenticatedSamPromoCodesRoute: AuthenticatedSamPromoCodesRoute,
  AuthenticatedSamReportsRoute: AuthenticatedSamReportsRoute,
  AuthenticatedSamIndexRoute: AuthenticatedSamIndexRoute,
}

const AuthenticatedSamRouteWithChildren =
  AuthenticatedSamRoute._addFileChildren(AuthenticatedSamRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAffiliateRoute: typeof AuthenticatedAffiliateRouteWithChildren
  AuthenticatedManagerRoute: typeof AuthenticatedManagerRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSamRoute: typeof AuthenticatedSamRouteWithChildren
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAffiliateRoute: AuthenticatedAffiliateRouteWithChildren,
  AuthenticatedManagerRoute: AuthenticatedManagerRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSamRoute: AuthenticatedSamRouteWithChildren,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ApiCustomerPlansRoute: ApiCustomerPlansRoute,
  ApiCustomerBillingUpdatePaymentMethodRoute:
    ApiCustomerBillingUpdatePaymentMethodRoute,
  ApiCustomerCouponValidateRoute: ApiCustomerCouponValidateRoute,
  ApiCustomerInvoicesCustomerIdRoute: ApiCustomerInvoicesCustomerIdRoute,
  ApiCustomerSubscriptionIdRoute: ApiCustomerSubscriptionIdRoute,
  ApiCustomerSubscriptionCancelRoute: ApiCustomerSubscriptionCancelRoute,
  ApiCustomerSubscriptionCreateRoute: ApiCustomerSubscriptionCreateRoute,
  ApiCustomerSubscriptionReactivateRoute:
    ApiCustomerSubscriptionReactivateRoute,
  ApiPublicHooksClearCommissionsRoute: ApiPublicHooksClearCommissionsRoute,
  ApiPublicHooksRetryEmailsRoute: ApiPublicHooksRetryEmailsRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
